version: '3.2'
services:
    mariadb:
        container_name: ${PROJECT_NAME}_mariadb
        build:
            context: "."
            dockerfile: "mariadb/Dockerfile"
        environment:
            MYSQL_DATABASE: ${MARIADB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
            TZ: Europe/Warsaw
        ports:
            - ${MARIADB_EXTERNAL_PORT}:3306
        volumes:
            - '/var/lib/mysql'
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: php-fpm
            args:
                uid: ${APP_USER_ID}
                gid: ${APP_GROUP_ID}
        ports:
            - "9000:9000"
        volumes:
            - ${ROOT_PATH}:/app:cached
        links:
            - mariadb
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
            - ${ROOT_PATH}:/app:cached

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        links:
            - mariadb
        ports:
            - 8180:80
        volumes:
            - /sessions
